version: "3.9"

services:
  db:
    image: postgres
    environment:
#in production variable should be stored in .env that should not be available in repository
      - POSTGRES_DB=car_api
      - POSTGRES_USER=car_api
      - POSTGRES_PASSWORD=car_api123
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
# env variablies can be automatically read from .env file in project root dir
#      - SECRET_KEY=${SECRET_KEY}
#      - DEBUG=${DEBUG}
# for demonstration purposes use some defaults
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
