# Generated by Django 2.2.17 on 2021-03-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210304_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate_model',
            new_name='car',
        ),
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
    ]
