# Generated by Django 2.2.17 on 2021-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210305_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
